# Drift-check signature for supplements/expression.md.
# Generated by scripts/check-doc-signatures.mjs.
# Re-bless via: node scripts/check-doc-signatures.mjs --bless supplements/expression.md
#
hash: 5be3fc0b349d30a92b523ba702c3405f4de06e119eeccc495f45cab243fbab13
blessedAt: 2026-05-09
tracked:
  - src/core/nodes/ExpressionNode.ts (1 file)
  - src/core/nodes/expressionUtils.ts (1 file)
  - src/core/expressions/ExpressionScope.ts (1 file)
