# Drift-check signature for authoring-features.md.
# Generated by scripts/check-doc-signatures.mjs.
# Re-bless via: node scripts/check-doc-signatures.mjs --bless authoring-features.md
#
hash: c1e791fbdc240c88a4adb97b1a65b6ae7618d788535694e2c0c7ab2c5b34dd46
blessedAt: 2026-05-08
tracked:
  - src/loader/expanders/instance-expand.ts (1 file)
  - src/loader/util/apply-param-overrides.ts (1 file)
  - src/loader/phases/01-param-overrides.ts (1 file)
  - src/core/GraphPort.ts (1 file)
  - src/core/GraphNode.ts (1 file)
